#*************************
#    General info
#*************************

### Get info
GET http://localhost:3001/info

#*************************
#    Phonebook Entries
#*************************

### Get all entries
GET http://localhost:3001/api/persons

### Get individual entry (found)
GET http://localhost:3001/api/persons/1

### Get individual entry (not found)
GET http://localhost:3001/api/persons/-1

### Delete individual entry (found)
DELETE  http://localhost:3001/api/persons/1

### Delete individual entry (not found)
DELETE  http://localhost:3001/api/persons/-1

### Post valid entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Frusciante",
    "number": "111-222-3333"
}

### Post invalid entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "111-222-3333"
}